apiVersion: v2
name: trino-hue
description: A Helm chart for deploying Trino and Apache Hue with integrated Trino editor support
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: trino
    version: "1.41.0"
    repository: "https://trinodb.github.io/charts/"
    condition: trino.enabled
  - name: hue
    version: "1.0.3"
    repository: "https://helm.gethue.com"
    condition: hue.enabled

