{{- if and .Values.hue.enabled .Values.hue.enableRemoteDebug }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-patch-hue-remote-debug-{{ .Release.Revision }}
  labels:
    app: {{ .Release.Name }}-hue
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-patch-hue-remote-debug
    spec:
      serviceAccountName: {{ .Release.Name }}-hue-patch
      restartPolicy: OnFailure
      containers:
      - name: patch-remote-debug
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          set -e
          echo "Configuring remote debugging for Hue deployment..."
          
          # Wait for the hue deployment to exist
          echo "Waiting for hue deployment to be created..."
          for i in $(seq 1 30); do
            if kubectl get deployment hue -n {{ .Release.Namespace }} &>/dev/null; then
              echo "Found hue deployment"
              break
            fi
            echo "Waiting for hue deployment... ($i/30)"
            sleep 2
          done
          
          # Install jq if not available
          if ! command -v jq &> /dev/null; then
            echo "Installing jq..."
            apk add --no-cache jq || apt-get update && apt-get install -y jq || yum install -y jq
          fi
          
          # Get the current deployment
          kubectl get deployment hue -n {{ .Release.Namespace }} -o json > /tmp/hue-deployment.json
          
          DEBUG_PORT="{{ .Values.hue.remoteDebug.port | default "5678" }}"
          DEBUG_WAIT="{{ .Values.hue.remoteDebug.waitForAttach | default false }}"
          
          echo "Configuring remote debugging on port ${DEBUG_PORT}"
          
          # Check if debugpy env vars are already set
          CURRENT_ENV=$(kubectl get deployment hue -n {{ .Release.Namespace }} -o jsonpath='{.spec.template.spec.containers[?(@.name=="hue")].env[*].name}' 2>/dev/null || echo "")
          
          if echo "$CURRENT_ENV" | grep -q "DEBUGPY_ENABLED"; then
            echo "Updating existing remote debug configuration..."
            cat /tmp/hue-deployment.json | jq --arg port "$DEBUG_PORT" --arg wait "$DEBUG_WAIT" '
              .spec.template.spec.containers[] |= if .name == "hue" then 
                .env |= map(
                  if .name == "DEBUGPY_ENABLED" then .value = "1"
                  elif .name == "DEBUGPY_PORT" then .value = $port
                  elif .name == "DEBUGPY_WAIT" then .value = $wait
                  else . end
                )
              else . end
            ' > /tmp/hue-deployment-updated.json
          else
            echo "Adding new remote debug configuration..."
            cat /tmp/hue-deployment.json | jq --arg port "$DEBUG_PORT" --arg wait "$DEBUG_WAIT" '
              .spec.template.spec.containers[] |= if .name == "hue" then 
                .env += [
                  {"name": "DEBUGPY_ENABLED", "value": "1"},
                  {"name": "DEBUGPY_PORT", "value": $port},
                  {"name": "DEBUGPY_WAIT", "value": $wait}
                ]
              else . end
            ' > /tmp/hue-deployment-updated.json
          fi
          
          # Add debug port to container ports if not present
          cat /tmp/hue-deployment-updated.json | jq --arg port "$DEBUG_PORT" '
            .spec.template.spec.containers[] |= if .name == "hue" then 
              if (.ports | map(.containerPort == ($port | tonumber)) | any | not) then
                .ports += [{"containerPort": ($port | tonumber), "name": "debugpy", "protocol": "TCP"}]
              else . end
            else . end
          ' > /tmp/hue-deployment-final.json
          
          kubectl apply -f /tmp/hue-deployment-final.json -n {{ .Release.Namespace }}
          
          echo "Remote debugging configured:"
          echo "  DEBUGPY_ENABLED=1"
          echo "  DEBUGPY_PORT=${DEBUG_PORT}"
          echo "  DEBUGPY_WAIT=${DEBUG_WAIT}"
          echo ""
          echo "To connect:"
          echo "  1. Port-forward: kubectl port-forward <hue-pod> ${DEBUG_PORT}:${DEBUG_PORT}"
          echo "  2. Attach VS Code debugger to localhost:${DEBUG_PORT}"
          
          echo "Restarting Hue deployment to apply changes..."
          kubectl rollout restart deployment/hue -n {{ .Release.Namespace }} || echo "Warning: Could not restart deployment"
          
          echo "Waiting for deployment to be ready..."
          kubectl rollout status deployment/hue -n {{ .Release.Namespace }} --timeout=120s || echo "Warning: Deployment may still be rolling out"
{{- end }}

