{{- if and .Values.hue.enabled .Values.hue.enableDebugLogging }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-patch-hue-debug-logging-{{ .Release.Revision }}
  labels:
    app: {{ .Release.Name }}-hue
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-patch-hue-debug-logging
    spec:
      serviceAccountName: {{ .Release.Name }}-hue-patch
      restartPolicy: OnFailure
      containers:
      - name: patch-debug-logging
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          set -e
          echo "Adding debug logging environment variables to Hue deployment..."
          
          # Wait for the hue deployment to exist
          echo "Waiting for hue deployment to be created..."
          for i in $(seq 1 30); do
            if kubectl get deployment hue -n {{ .Release.Namespace }} &>/dev/null; then
              echo "Found hue deployment"
              break
            fi
            echo "Waiting for hue deployment... ($i/30)"
            sleep 2
          done
          
          # Install jq if not available
          if ! command -v jq &> /dev/null; then
            echo "Installing jq..."
            apk add --no-cache jq || apt-get update && apt-get install -y jq || yum install -y jq
          fi
          
          # Get the current deployment
          kubectl get deployment hue -n {{ .Release.Namespace }} -o json > /tmp/hue-deployment.json
          
          # Determine log level
          {{- if eq .Values.hue.logLevel "DEBUG" }}
          LOG_LEVEL="DEBUG"
          DESKTOP_DEBUG="1"
          {{- else }}
          LOG_LEVEL="{{ .Values.hue.logLevel | default "INFO" }}"
          DESKTOP_DEBUG=""
          {{- end }}
          
          echo "Setting log level to: ${LOG_LEVEL}"
          
          # Check if logging env vars are already set
          CURRENT_ENV=$(kubectl get deployment hue -n {{ .Release.Namespace }} -o jsonpath='{.spec.template.spec.containers[?(@.name=="hue")].env[*].name}' 2>/dev/null || echo "")
          
          if echo "$CURRENT_ENV" | grep -q "DESKTOP_LOGLEVEL"; then
            echo "Updating existing logging environment variables..."
            # Update existing env vars
            cat /tmp/hue-deployment.json | jq --arg loglevel "$LOG_LEVEL" --arg debug "$DESKTOP_DEBUG" '
              .spec.template.spec.containers[] |= if .name == "hue" then 
                .env |= map(
                  if .name == "DESKTOP_LOGLEVEL" then .value = $loglevel
                  elif .name == "DESKTOP_DEBUG" then .value = $debug
                  else . end
                ) | 
                .env |= if ($debug != "" and (. | map(.name == "DESKTOP_DEBUG") | any | not)) then . + [{"name": "DESKTOP_DEBUG", "value": $debug}] else . end |
                .env |= map(select(.name != "DESKTOP_DEBUG" or .value != ""))
              else . end
            ' > /tmp/hue-deployment-updated.json
          else
            echo "Adding new logging environment variables..."
            # Add new env vars
            cat /tmp/hue-deployment.json | jq --arg loglevel "$LOG_LEVEL" --arg debug "$DESKTOP_DEBUG" '
              .spec.template.spec.containers[] |= if .name == "hue" then 
                .env += [
                  {"name": "DESKTOP_LOGLEVEL", "value": $loglevel}
                ] + (if $debug != "" then [{"name": "DESKTOP_DEBUG", "value": $debug}] else [] end)
              else . end
            ' > /tmp/hue-deployment-updated.json
          fi
          
          kubectl apply -f /tmp/hue-deployment-updated.json -n {{ .Release.Namespace }}
          
          echo "Debug logging environment variables configured:"
          echo "  DESKTOP_LOGLEVEL=${LOG_LEVEL}"
          {{- if eq .Values.hue.logLevel "DEBUG" }}
          echo "  DESKTOP_DEBUG=1"
          {{- end }}
          
          echo "Restarting Hue deployment to apply changes..."
          kubectl rollout restart deployment/hue -n {{ .Release.Namespace }} || echo "Warning: Could not restart deployment"
          
          echo "Waiting for deployment to be ready..."
          kubectl rollout status deployment/hue -n {{ .Release.Namespace }} --timeout=120s || echo "Warning: Deployment may still be rolling out"
{{- end }}

